### ISSUE TITLE
r

### ISSUE THREAD

**Issue by jdev082** [ScolderCreations/r#2]
r?

**Comment by ScolderCreations** [comment]
r.

to be specific this is gonna be some sorta ‘Scratch algorithm’ that recommends projects based on your interests

of course i’m having trouble so it’s not done

**Comment by jdev082** [comment]
> r.
> 
> to be specific this is gonna be some sorta ‘Scratch algorithm’ that recommends projects based on your interests
> 
> of course i’m having trouble so it’s not done

I'm not liking the sound of that... data collection... nope im outa here.

**Comment by ScolderCreations** [comment]
> > r.
> > to be specific this is gonna be some sorta ‘Scratch algorithm’ that recommends projects based on your interests
> > of course i’m having trouble so it’s not done
> 
> I'm not liking the sound of that... data collection... nope im outa here.

Oh don’t worry. It’s manual information, you choose what you want to see. I never liked automatic recommendations, YouTube keeps trying to give me anime…

**Comment by ScolderCreations** [comment]
Well the entire project is going for a different idea… Still gonna be called R. Yep.
